### ISSUE TITLE
OS dependent behavior for JSplitPane's dividerLocation

### ISSUE THREAD

**Issue by tloehr** [kirill-grouchnikov/trident#2]
First let me thank for this superb animation library provided by You. While using it in my software project I found a strange yet funny behavior which I couldn't fix myself. Even after looking through Your sources.

I use the timeline function for animated slides between the two sides of a JSplitPane. This gives the application a little mac os like look and feel.

Anyways, the special thing about those splitpanes is, that you can set the location of the divider by an integer OR by a double.
So the JSplitPane class has a dividerLocation property which is an int but two methods for setting its value.

Now, if you use a Mac or a Windows machine the interpolate mechanism expects to run between two integers. If You use a Linux machine it expects to run between two doubles. Otherwise you will get loads of exceptions.

I created a small os dependent workaround for this problem, but I was hoping that You could find a better way than this. I am not sure if You need more information, or if I should create a small example in order to find the problem more quickly.

Here is a small excerpt of my workaround for it. Surely nothing I am proud of ;-)

``` java
public static double showSide(JSplitPane split, double pos, int speedInMillis) {
        if (Main.isAnimation()) {
            Object start;
            Object stop;
            if (Tools.isMac() || Tools.isWindows()) {
                start = new Integer(split.getDividerLocation());
                stop = new Integer(getDividerInAbsolutePosition(split, pos));
            } else {
                start = new Double(split.getDividerLocation() / getDividerInAbsolutePosition(split, 1.0d));
                stop = new Double(pos);
            }

            final Timeline timeline1 = new Timeline(split);
            timeline1.setEase(new Spline(0.9f));
            timeline1.addPropertyToInterpolate("dividerLocation", start, stop);
            timeline1.setDuration(speedInMillis);
            timeline1.play();
        } else {
            split.setDividerLocation(pos);
        }
        return pos;
    }
```

If more information is necessary, please feel free to contact me.

Thanks,

Torsten...

**Comment by kirill-grouchnikov** [comment]
Closing six-year old issue
