### ISSUE TITLE
TridentConfig's classloader related code does not allow loading of the properties file in certain cases.

### ISSUE THREAD

**Issue by kosakriszi** [kirill-grouchnikov/trident#4]
I am using Trident in a context where the classloader that loads the jar file is not the same as the thread's classloader that loads the class, which causes the Interpolater to be missing for the float type. I was able to fix this by changing the line to "ClassLoader classLoader = this.getClass().getClassLoader();", but I'm not sure if this is applicable to all cases.

**Comment by kirill-grouchnikov** [comment]
Looking at that in hindsight, that entire part of Trident is an overkill. TridentConfig.getInstance() already allows apps to add custom UI toolkit handlers and property interpolators. 

While originally (long time ago) I wanted Trident to be UI toolkit-agnostic, things have changed quite dramatically around it. Android has a very capable and a very performant set of animation APIs, and adding support for SWT animations was more of a distraction.

I was already planning to remove all bits related to SWT and Android. And while I'm at that, I'm going to simplify the initialization of TridentConfig to explicitly add all Swing-specific parts, with no ClassLoader awkwardness.

**Comment by kosakriszi** [comment]
That sounds awesome, I'm looking forward to it! Thanks for you answer.

**Comment by kirill-grouchnikov** [comment]
Just uploaded the latest sources and prebuilt binaries.
